## argo-diff
FROM ghcr.io/vince-riv/argo-diff:2.9.0 AS argo-diff

## ArgoCD
#ARG  ARGOCD_VERSION
#FROM quay.io/argoproj/argocd:v3.3.9 AS argocd

#COPY --from=argocd --chmod=755 /usr/local/bin/argocd /usr/local/bin/argocd

CMD ["/app/argo-diff"]
