---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-diff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-diff
  template:
    metadata:
      labels:
        app: argo-diff
    spec:
      imagePullSecrets:
        - name: ecr-login
      containers:
        - name: worker
          image: argo-diff:CHANGEME
          imagePullPolicy: Always
          #imagePullPolicy: IfNotPresent
          resources: {}
          #  limits:
          #    cpu: 250m
          #    memory: 250Mi
          #  requests:
          #    cpu: 10m
          #    memory: 45Mi
          #env:
          #  - name: AWS_DEFAULT_REGION
          #    value: us-east-1
