---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - deployment.yaml
  - env-secret.yaml
  - ingressroute.yaml
  - service.yaml

images:
  - name: argo-diff
    newName: 529264564500.dkr.ecr.us-east-1.amazonaws.com/argo-diff
    newTag: sha-4816f43
